CLS
PRINT "Bitte Pause drÅcken und Return fÅr weiter."
PRINT "Dieses ist ein Programm zum testen des Joysticks die ersten beiden Spalten"
PRINT "sind fÅr die Knîpfe, die dritte ist fÅr links(1)/rechts(ca.30) und die vierte"
PRINT "ist fÅr oben(1)/unten(5), in der Grund stellung sollten die Werte auf"
PRINT " 0  0 ca140 128 stehen,dieses Programm wurde mit einem PC Fighter getested."
10 PRINT STRIG(1); STRIG(5);
15 PRINT STRIG(3); STRIG(7);
20 PRINT STICK(0); STICK(1);
30 PRINT STICK(2); STICK(3)
GOTO 10

