      CLS
COLOR 15
LOCATE 5

LOCATE , 26
      PRINT "лл   лл"
LOCATE , 26
      PRINT " лл лл   ллллл    лл   лл"
LOCATE , 26
      PRINT "  ллл   лл   лл   лл   лл"
LOCATE , 26
      PRINT "л  лл   лл   лл   лл   ллл"
LOCATE , 26
      PRINT " ллл     ллллл     ллллл лл"
      PRINT
      PRINT
LOCATE , 13
      PRINT "лллл         лллл  ллллллллл   лллллллл    ллллл   лл"
LOCATE , 13
      PRINT "  ллл       ллл       ллл        ллл ллл   ллл    лллл"
LOCATE , 13
      PRINT "   ллл ллл ллл        ллл        ллл  ллл  ллл     лл"
LOCATE , 13
      PRINT "    лллл лллл         ллл        ллл   ллл ллл    "
LOCATE , 13
      PRINT "  лллл     лллл    ллллллллл   ллллл    лллллллл   лл"

